name: lint
on:
  push:
    branches:
      - main
      - dev
  pull_request:
permissions:
  contents: read
jobs:
  build:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: ^1.19
      - name: Go Lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
      - name: Test
        run: go test -shuffle on ./...
